# Generated by Django 4.2.4 on 2023-10-31 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('registered', 'Зарегистрирован'), ('moderating', 'Проверяется'), ('approved', 'Принято'), ('denied', 'Отказано'), ('deleted', 'Удалено')], max_length=255, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('approving_date', models.DateField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('deleted', 'deleted')], default='enabled', max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='', max_length=100, verbose_name='Логин')),
                ('password', models.CharField(default='', max_length=100, verbose_name='Пароль')),
                ('isModerator', models.BooleanField(default=False, verbose_name='Является модератором')),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('info', models.TextField(default='')),
                ('src', models.TextField(default='')),
                ('status', models.CharField(choices=[('enabled', 'enabled'), ('deleted', 'deleted')], max_length=255)),
                ('id_category', models.ForeignKey(blank=True, db_column='id_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscription', to='transport_subscription_app.category')),
            ],
            options={
                'db_table': 'subscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApplicationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_application', models.ForeignKey(db_column='id_application', on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscription_app.application')),
                ('id_subscription', models.ForeignKey(db_column='id_subscription', on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscription_app.subscription')),
            ],
            options={
                'db_table': 'application_subscription',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='id_moderator',
            field=models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_application', to='transport_subscription_app.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, related_name='user_application', to='transport_subscription_app.user'),
        ),
        migrations.AddConstraint(
            model_name='applicationsubscription',
            constraint=models.UniqueConstraint(fields=('id_application', 'id_subscription'), name='composite_key'),
        ),
    ]
