# Generated by Django 4.2.4 on 2023-10-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('deleted', 'deleted')], default='enabled', max_length=255),
        ),
    ]
