# Generated by Django 4.2.4 on 2023-10-16 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0002_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='id_moderator',
            field=models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_application', to='transport_subscription_app.user'),
        ),
    ]
