# Generated by Django 4.2.4 on 2023-10-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0003_alter_application_id_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_application', models.ForeignKey(db_column='id_application', on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscription_app.application')),
                ('id_subscription', models.ForeignKey(db_column='id_subscription', on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscription_app.subscription')),
            ],
            options={
                'db_table': 'test',
                'unique_together': {('id_application', 'id_subscription')},
            },
        ),
    ]
