# Generated by Django 4.2.4 on 2023-12-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0003_customuser_full_name_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': True},
        ),
    ]
