# Generated by Django 4.2.4 on 2023-10-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0004_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
