# Generated by Django 4.2.4 on 2023-12-19 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0005_subscription_active_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='active_date',
        ),
    ]
