# Generated by Django 4.2.4 on 2024-01-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscription_app', '0006_remove_subscription_active_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'managed': False},
        ),
    ]
