# Generated by Django 4.2.4 on 2023-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Пароль')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
