# Generated by Django 4.2.4 on 2023-10-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscriptions_back_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationSubscription',
        ),
    ]
