# Generated by Django 4.2.4 on 2023-10-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscriptions_back_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionsRates',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_rates',
                'managed': True,
            },
        ),
    ]
