# Generated by Django 4.2.4 on 2023-10-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscriptions_back_app', '0002_subscriptionsrates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='rate_names',
        ),
        migrations.RemoveField(
            model_name='subscriptions',
            name='rate_prices',
        ),
    ]
