# Generated by Django 4.2.4 on 2023-10-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscriptions_back_app', '0002_delete_applicationsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_application', models.ForeignKey(db_column='id_application', on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscriptions_back_app.application')),
                ('id_subscription', models.ForeignKey(db_column='id_subscription', on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscriptions_back_app.subscription')),
            ],
            options={
                'db_table': 'application_subscription',
            },
        ),
        migrations.AddConstraint(
            model_name='applicationsubscription',
            constraint=models.UniqueConstraint(fields=('id_application', 'id_subscription'), name='composite_key'),
        ),
    ]
