# Generated by Django 4.2.4 on 2023-10-10 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscriptions_back_app', '0003_applicationsubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
