# Generated by Django 4.2.4 on 2023-10-03 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_subscriptions_back_app', '0003_remove_subscriptions_rate_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionsrates',
            name='id_subscriptions',
            field=models.ForeignKey(blank=True, db_column='id_subscriptions', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transport_subscriptions_back_app.subscriptions'),
        ),
    ]
